[package]
name = "slint-wordle"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "slint-wordle"
path = "src/main.rs"

[build-dependencies]
slint-build = { git = "https://github.com/slint-ui/slint", rev = "5e122db954f9e92c26b1924c021b8c8ece323908" }

[dependencies]
zstd = "0.13.3"
rand = "0.10.2"

[target.'cfg(not(all(target_arch = "arm", target_os = "linux", target_env = "musl")))'.dependencies]
slint = { git = "https://github.com/slint-ui/slint", rev = "5e122db954f9e92c26b1924c021b8c8ece323908", features = ["std", "compat-1-2", "renderer-software"] }

[target.'cfg(all(target_arch = "arm", target_os = "linux", target_env = "musl"))'.dependencies]
slint = { git = "https://github.com/slint-ui/slint", rev = "5e122db954f9e92c26b1924c021b8c8ece323908", default-features = false, features = ["std", "compat-1-2", "renderer-software", "software-renderer-path", "unstable-fontique-011"] }
slint-backend-kindle = { git = "https://github.com/justinledwards/ferrink-home-assistant", rev = "1567d66ea0d782d559b55cbf006ebedc0605f8e7", package = "slint-backend-kindle" }
fontique = { version = "0.11", default-features = false, features = ["std", "fontconfig-dlopen"] }
fontdb = { version = "0.23", default-features = false, features = ["std", "fs", "memmap"] }

[patch.crates-io]
slint = { git = "https://github.com/slint-ui/slint", rev = "5e122db954f9e92c26b1924c021b8c8ece323908" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
